### ISSUE TITLE
UTF-8 spamming console

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#177]
Randomly ScoreboardStats started spamming my console with this error:
```
java.lang.IllegalStateException: java.io.EOFException
        at guava10.com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[ByteStreams$ByteArrayDataInputStream.class:1.7.10-1614.58]
        at com.github.games647.scoreboardstats.variables.defaults.BungeeCordVariables.onPluginMessageReceived(BungeeCordVariables.java:62) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [StandardMessenger.class:1.7.10-1614.58]
        at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java:2684) [nh.class:?]
        at net.minecraft.network.play.client.C17PacketCustomPayload.func_148833_a(C17PacketCustomPayload.java:69) [iz.class:?]
        at net.minecraft.network.play.client.C17PacketCustomPayload.func_148833_a(C17PacketCustomPayload.java:84) [iz.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340) ~[?:1.8.0_111]
        at java.io.DataInputStream.readUTF(DataInputStream.java:589) ~[?:1.8.0_111]
        at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_111]
        at guava10.com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[ByteStreams$ByteArrayDataInputStream.class:1.7.10-1614.58]
        ... 12 more
```
I didn't change nothing, I'm sure, and then it started happening...

**Comment by games647** [comment]
What version do you use?

**Comment by Eufranio** [comment]
ScoreboardStats v0.10.1 (downloaded from the Bukkit page)

**Comment by games647** [comment]
The line numbers aren't correct. Please check again. Moreover this exception is already caught in https://github.com/games647/ScoreboardStats/commit/728183d95c193b395ffb8ca65c36eaafd2fd5350

**Comment by Eufranio** [comment]
Hmm... This means the version I'm using is very old?

**Comment by games647** [comment]
I don't know, but this bug is fixed since that commit and the uploaded version as different line numbers than this stacktrace.

**Comment by Eufranio** [comment]
Hmm, are you sure the branch is correct with the latest version of ScoreboardStats? I downloaded this build again and still having this error =/

**Comment by games647** [comment]
I download it from devBukkit and check the line numbers from the bytecode.

**Comment by Eufranio** [comment]
Well, if you say it's already fixed... :X

**Comment by Eufranio** [comment]
who am i to disagree

**Comment by games647** [comment]
You could upload the file and I look into it.

**Comment by Eufranio** [comment]
[ScoreboardStats.jar](http://frani.magitechserver.cf/Pessoal/ScoreboardStats.jar)

**Comment by games647** [comment]
The file size is even different. The new file has ~316KB. The uploaded file has ~140KB. Maybe a bug in the dev-bukkit website. 

Could you try it from here: https://dev.bukkit.org/projects/scoreboardstats/files
