### ISSUE TITLE
Incorrect Askyblock island levels

### ISSUE THREAD

**Issue by YellowZaki** [games647/ScoreboardStats#181]
The scoreboard is showing incorrect islands levels (less levels than expected).

**Comment by YellowZaki** [comment]
@games647 I have fixed this, could you give me the permission to push the change?

**Comment by games647** [comment]
Isn't this already fixed with https://github.com/games647/ScoreboardStats/commit/434b8919474ffd00c3a7c182909aa7886c438c5b ? If I would really appreciate a pull request.

**Comment by YellowZaki** [comment]
No, you missed to change some island_level to island-level on ASkyBlockVariables.java
